### ISSUE TITLE
DeviceManager: getParameters method

### ISSUE THREAD

**Issue by ItsTimmy** [WVU-Home-Auto/OasisServer#13]
This method is basically a proxy for the Device class' getParameters method.

This method takes one argument: The device's unique ID. It returns the result of calling getParameters() on the Device corresponding to that ID. (So basically, look it up in the map you created in #6 )

**Comment by ItsTimaiFool** [comment]
This method might need to be optimized later, because each device's getParameter method will probably have to communicate over the network with the physical device. If this ends up being a problem, we can change DeviceManager's getParameters method to cache parameters of each device.
