### ISSUE TITLE
DeviceManager: list of devices

### ISSUE THREAD

**Issue by WVU-Home-Auto** [WVU-Home-Auto/OasisServer#6]
The device manager should maintain a list of all Devices that have been registered with the registerDevice() method. This list should be structured such that devices can be retrieved from the list by ID.

**Comment by ItsTimaiFool** [comment]
This isn't any particular method, this is just the back end for doing the actual storage of device information. The devices should be stored in a Map, similarly to how recipes are stored in the EventListeners class. The key will be the device's unique ID, and the value will be a JSON object containing all of the device's parameters (from the getParameters() method of the Device class).

**Comment by ItsTimaiFool** [comment]
I'm just now realizing some major flaws with all of this. With the method I just specified, no one is keeping a reference to all of the instances of the Device class, so they'll just get garbage collected. This will require some thought. If anyone has any ideas, let me know.
